# /etc/fail2ban/jail.d/immich-auth.conf
[immich-auth]
enabled = true
filter = immich-auth
backend = polling
logpath = /var/lib/docker/volumes/YOUR_NPM_VOLUME/_data/logs/proxy-host-N_access.log
maxretry = 10
findtime = 300
bantime = 3600
action = iptables-allports[actiontype=<multiport>, chain=DOCKER-USER]
